### ISSUE TITLE
Tradeoff error

### ISSUE THREAD

**Issue by said3427** [micom-dev/q2-micom#3]
I am using a skin microbiome dataset, I already calculated the models, minimal medium, growth. I tried to validate the trade-off but I got some errors:

Command:
```bash
qiime micom tradeoff --i-models models.qza \
	--i-medium minimal_medium.qza \
	--p-threads 40 \
	--o-results tradeoff.qza \
	--verbose
```
Error:
```bash
2020-04-02 17:48:31.066 | WARNING  | micom.solution:solve:217 - solver encountered an error infeasible
Process Process-6:
Traceback (most recent call last):
  File "/home/said/anaconda3/envs/qiime2-dev/lib/python3.6/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
  File "/home/said/anaconda3/envs/qiime2-dev/lib/python3.6/multiprocessing/process.py", line 93, in run
    self._target(*self._args, **self._kwargs)
  File "/home/said/anaconda3/envs/qiime2-dev/lib/python3.6/site-packages/micom/workflows.py", line 9, in _process
    res = f(args)
  File "/home/said/anaconda3/envs/qiime2-dev/lib/python3.6/site-packages/q2_micom/_tradeoff.py", line 25, in _tradeoff
    rates = sol.members
AttributeError: 'NoneType' object has no attribute 'members'
```
I followed the process for a while and it seems like it will never end for that Process-6 error.

**Comment by cdiener** [comment]
I see probably needs some more handling for numerical problems like `micom grow`. I will get on it.

**Comment by cdiener** [comment]
Okay I added additional tests to the minimal medium and tradeoff commands. You will need to update to version 0.6.3 or later. This can be done in your Qiime 2 environment with:

```bash
pip install -U q2-micom
```
This should update it to the latest version. I would suggest also running the minimal medium step again since it will now tell you if a particular sample can never grow.
