### ISSUE TITLE
per sample diet model

### ISSUE THREAD

**Issue by Mechah** [micom-dev/q2-micom#8]
Hey, I created an adapted per sample diet model with the following structure for my dataset:

	flux	dilution	metabolite	reaction	sample_id
0	0.000135232	0.1	fru_m	EX_fru_m	ORS18-017
1	0.000329774	0.1	glc_m	EX_glc_m	ORS18-017
2	4.99876E-05	0.1	gal_m	EX_gal_m	ORS18-017
3	0.0148986	0.1	man_m	EX_man_m	ORS18-017
4	0.000161329	0.1	mnl_m	EX_mnl_m	ORS18-017
5	0.0148986	0.1	fuc_L_m	EX_fuc_L_m	ORS18-017

However, after import as --type MicomMedium[PerSample] I receive the following error with the qiime micom grow command:

Plugin error from micom:

  'DataFrame' object has no attribute 'reaction'

Hope you can help!
Thanks!

**Comment by cdiener** [comment]
What file type did you import? Media have to be CSV files not tab-delimited. Also the initial index column (0, 1, 2, ...) has to be removed.

**Comment by Mechah** [comment]
I used CSV and removed the initial index column, but I received the same error again...

Traceback (most recent call last):
  File "/home/cluster/o_mahnerta/miniconda3/envs/qiime2-2020.2_new/lib/python3.6/site-packages/q2cli/commands.py", line 328, in __call__
    results = action(**arguments)
  File "</home/cluster/o_mahnerta/miniconda3/envs/qiime2-2020.2_new/lib/python3.6/site-packages/decorator.py:decorator-gen-243>", line 2, in grow
  File "/home/cluster/o_mahnerta/miniconda3/envs/qiime2-2020.2_new/lib/python3.6/site-packages/qiime2/sdk/action.py", line 245, in bound_callable
    output_types, provenance)
  File "/home/cluster/o_mahnerta/miniconda3/envs/qiime2-2020.2_new/lib/python3.6/site-packages/qiime2/sdk/action.py", line 390, in _callable_executor_
    output_views = self._callable(**view_args)
  File "/home/cluster/o_mahnerta/miniconda3/envs/qiime2-2020.2_new/lib/python3.6/site-packages/q2_micom/_growth.py", line 25, in grow
    manifest, model_folder, medium, tradeoff, threads)
  File "/home/cluster/o_mahnerta/miniconda3/envs/qiime2-2020.2_new/lib/python3.6/site-packages/micom/workflows/grow.py", line 97, in grow
    medium = process_medium(medium, samples)
  File "/home/cluster/o_mahnerta/miniconda3/envs/qiime2-2020.2_new/lib/python3.6/site-packages/micom/workflows/media.py", line 14, in process_medium
    medium.index = medium.reaction
  File "/home/cluster/o_mahnerta/miniconda3/envs/qiime2-2020.2_new/lib/python3.6/site-packages/pandas/core/generic.py", line 5179, in __getattr__
    return object.__getattribute__(self, name)
AttributeError: 'DataFrame' object has no attribute 'reaction'

Plugin error from micom:

  'DataFrame' object has no attribute 'reaction'

**Comment by cdiener** [comment]
Assuming your imported file is called `medium.qza`. Could you run:

```python3
import qiime2 as q2                                                                                                                                                                    
import pandas as pd                                                                                                                                                                    

art = q2.Artifact.load("medium.qza")                                                                                                                                                   
art.view(pd.DataFrame)                                                                                                                                                                 
```

in your Qiime 2 env and post the output please.

**Comment by Mechah** [comment]
I solved my error: 
Unfortunately, my CSV export from Excel used semicolons and not commas as default separator... (I did not double check)
Thanks for your help Christian and sorry for bothering you!

**Comment by cdiener** [comment]
No problem 😁 Yeah I should use a more strict validation for the medium type. I'll leave that issue open but will change the title.
